sudo: required
language: go
services:
- docker
go:
- 1.9.3
before_install:
install:
- go get -u github.com/ory/ladon
- go get -u github.com/ory/pagination
- go get -u github.com/gin-gonic/gin
- go build .
