#!/usr/bin/env bash

OUTPUT=${1:-bin/iamprototype}

echo "Building iamprototype ..."
mkdir -p bin
go get -u github.com/ory/ladon
go get -u github.com/ory/pagination
go get -u github.com/gin-gonic/gin
go build -o $OUTPUT .